<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Nazionale</name>
   <tag></tag>
   <elementGuidId>f750eddf-f446-403f-aa32-0e42b24d0480</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@onclick=&quot;showReg('Nazionale')&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3b4c731e-f1ae-4cf1-bbf3-3fb5c05db7d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>showReg('Nazionale')</value>
      <webElementGuid>4c3e3f10-6028-41f3-aa57-cfd310b61875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nazionale</value>
      <webElementGuid>9a1f28fa-00dd-41f3-ac95-2ff8c3f5b325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;all-mon&quot;]/div[@class=&quot;border&quot;]/div[@class=&quot;all-filter&quot;]/div[@class=&quot;dropdown-reg active&quot;]/div[@class=&quot;option&quot;]/div[21]</value>
      <webElementGuid>255113f8-38c4-4371-a513-084423b3a0b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@onclick=&quot;showReg('Nazionale')&quot;]</value>
      <webElementGuid>e5a7366b-5910-4c27-aef3-6158c1fb5604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Veneto'])[1]/following::div[1]</value>
      <webElementGuid>09c78831-4a1f-4c9e-8dac-ae336d3e4997</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Valle d', &quot;'&quot;, 'Aosta')])[1]/following::div[2]</value>
      <webElementGuid>09d35be5-f7e7-4370-9f76-a189d16437ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cerca'])[1]/preceding::div[1]</value>
      <webElementGuid>43419980-f8d3-423b-957c-9e0eed86f41c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Per navigare, premi i tasti freccia.'])[1]/preceding::div[96]</value>
      <webElementGuid>be9fc7a4-9069-47d1-8941-782f3ecc8530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nazionale']/parent::*</value>
      <webElementGuid>2764b74e-69fd-44f7-85c2-bed02d5669c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[21]</value>
      <webElementGuid>ff1cb8ef-1b70-40bf-a77b-0a53cfc6db5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Nazionale' or . = 'Nazionale')]</value>
      <webElementGuid>48c01986-3ed6-462f-a2b3-fa3b07762b5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
