<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Cerca</name>
   <tag></tag>
   <elementGuidId>3469f55d-a39a-48fb-80da-b263bdbe792f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@onclick='seleziona()']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.submit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b61a74a6-6736-40c8-8dc3-95682f4fd0df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>14879dce-3bb4-48c1-bb3e-491c39262905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>seleziona()</value>
      <webElementGuid>1439e2d1-abed-40ad-b6e0-be7c2ecd412d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cerca</value>
      <webElementGuid>3f614a75-02fb-4baa-9594-67f5574906d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;all-mon&quot;]/div[@class=&quot;border&quot;]/div[@class=&quot;all-filter&quot;]/div[@class=&quot;submit&quot;]</value>
      <webElementGuid>6fb9368a-8093-4a06-8c86-4ab89f06cfad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@onclick='seleziona()']</value>
      <webElementGuid>b73bc69c-990e-40fe-8fc1-c0ca8b10eb0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nazionale'])[1]/following::div[1]</value>
      <webElementGuid>fdd6a00a-395b-4ba6-8d50-208959e178db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Veneto'])[1]/following::div[2]</value>
      <webElementGuid>7ab66ef9-29f6-45bc-9322-df42dcc1ef08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Per navigare, premi i tasti freccia.'])[1]/preceding::div[95]</value>
      <webElementGuid>6f1688a1-f9aa-499c-921d-2493b0460718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='←'])[1]/preceding::div[100]</value>
      <webElementGuid>9b370bc9-662d-4598-9d1f-fd9bd59c18ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cerca']/parent::*</value>
      <webElementGuid>4ae76780-50a6-4a99-8cd0-7b2a54eefe44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]</value>
      <webElementGuid>683c28bc-5beb-4023-bfa7-640e951fb71b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Cerca' or . = 'Cerca')]</value>
      <webElementGuid>19ed4915-8ff6-481a-9438-c27ee2ccea35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
