<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Calcolo CO2_regione</name>
   <tag></tag>
   <elementGuidId>7d3ed8c3-5d3f-4aa4-90b1-8d4b2ac6a127</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='regione']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#regione</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fd86be1a-8fbf-4d88-bef3-af713d3761b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>53c6a0e9-0e8d-46ac-bea6-e332a9ad0abe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filterBox-reg</value>
      <webElementGuid>7b94f7a9-56fc-4c32-9d1a-4baf297fee46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Regioni</value>
      <webElementGuid>348b17f2-3018-4d25-b40a-c5166ddb1ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>regione</value>
      <webElementGuid>ef49290f-ead3-453b-a93e-46246baa0b21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;regione&quot;)</value>
      <webElementGuid>db4e2aad-f83d-4ec5-b1a0-b39d3c5a66fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='regione']</value>
      <webElementGuid>2cf6b663-5061-4b0a-b8d8-e898130e16a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>a8c53f30-f050-4baa-af0f-494afe82b55f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'regione']</value>
      <webElementGuid>43d5d5e2-c00a-4e3d-98b4-a2b9ec90a3a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
