<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Vai al risultato</name>
   <tag></tag>
   <elementGuidId>19c53b91-842e-448d-a577-f70a876478ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.go</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='calcola()']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>88af7ea4-e240-4775-84c6-4c520f0a20d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>go</value>
      <webElementGuid>4bb6514a-5026-4a34-bfd8-50806f8349a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>calcola()</value>
      <webElementGuid>27c418ac-b82b-4062-8826-8de15297a590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vai al risultato</value>
      <webElementGuid>b910306c-687f-4644-a91b-224e8d8f20c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;km&quot;)/div[@class=&quot;big-box&quot;]/a[@class=&quot;go&quot;]</value>
      <webElementGuid>16c8ac56-bbb7-49ae-bf6f-d9386c8da883</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='calcola()']</value>
      <webElementGuid>1ba4eac8-8762-4784-bf4b-b1a6744369fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='km']/div/a</value>
      <webElementGuid>ea83a9ef-44d3-420d-941a-714a24c19482</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Vai al risultato')]</value>
      <webElementGuid>8433957b-77da-4e18-bde2-452f45f19c1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quanti km hai percorso?'])[1]/following::a[1]</value>
      <webElementGuid>6a3f3a3c-b0a3-431f-8efa-daafe46e0543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hai già scoperto quanta CO2 hai causato?'])[1]/following::a[1]</value>
      <webElementGuid>5c546f27-543d-4392-9856-5c86d95fafaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chi siamo?'])[1]/preceding::a[1]</value>
      <webElementGuid>750c17e6-fe2a-4f9d-a708-f54b878b4992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Info'])[1]/preceding::a[1]</value>
      <webElementGuid>6353b351-f687-4bd7-8eed-0072b102e3fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Vai al risultato']/parent::*</value>
      <webElementGuid>fbeab8f8-eb4e-49cc-911b-07522e5774fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>6548b953-979f-4526-b171-3842cb373196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Vai al risultato' or . = 'Vai al risultato')]</value>
      <webElementGuid>d3a0d8c4-2649-440a-bc35-1ea06f2b727e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
