<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Mare_risorseimgscooter.png</name>
   <tag></tag>
   <elementGuidId>4137829e-b013-49d6-846d-80336bf89beb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='risorse\img\scooter.png']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2adac1f8-f477-42f8-942a-f1f31aa4c075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mezzo</value>
      <webElementGuid>16a32be7-42f3-4b1b-b8af-8ec63b6dc38e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>risorse\img\scooter.png</value>
      <webElementGuid>2a7aade2-fb2a-4458-bca9-7c90c0da8e6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>attiva(this)</value>
      <webElementGuid>6ff46e90-7094-4c3b-9d53-9c255aa0fad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;risorse\img\scooter.png&quot;)</value>
      <webElementGuid>363ae914-7682-46be-a4ea-92d4ca2ea07f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='risorse\img\scooter.png']</value>
      <webElementGuid>73ab7973-1b10-40d8-bc72-4863dba89606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='all-page']/div/div/div[2]/div[7]</value>
      <webElementGuid>d1a61bc7-4f50-4124-86e5-95344dd3b46d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mare'])[1]/following::div[8]</value>
      <webElementGuid>29a7a26e-a0fa-4847-948e-88c9eee26af0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aria'])[1]/following::div[8]</value>
      <webElementGuid>27871e69-2efb-4cc1-bf7c-c7e3f65864ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hai già scoperto quanta CO2 hai causato?'])[1]/preceding::div[4]</value>
      <webElementGuid>3cb064a3-9098-4bf2-b194-758cfd35fbcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quanti km hai percorso?'])[1]/preceding::div[8]</value>
      <webElementGuid>aa2c04b0-ec9d-4982-9bf2-cd869fbf75d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]</value>
      <webElementGuid>3e9b96d4-cdc4-47c4-9312-a9411323dfd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'risorse\img\scooter.png']</value>
      <webElementGuid>b39e6281-b4f5-4dd6-9326-870c1b03ffc0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
