<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Hai gi scoperto quanta CO2 hai causato_qui</name>
   <tag></tag>
   <elementGuidId>9ed5d3fc-49ed-4929-846a-470aebb9088a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#qui</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='qui']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cac7f98c-644f-41b6-ab67-9e526bd3bf07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4b867ccf-2150-4258-9159-9672e25d32f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>qui</value>
      <webElementGuid>45bb530b-88ea-479b-bb3c-d48745017ad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1296</value>
      <webElementGuid>524745e6-068a-412a-8bbd-9298290bc96a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qui&quot;)</value>
      <webElementGuid>e1d615cd-314b-4787-b8dc-9fe0f12db870</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='qui']</value>
      <webElementGuid>67839277-dfde-4636-a1ae-87bb6a72b8b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='all-page']/div[3]/div/div/input</value>
      <webElementGuid>7c291308-71e4-4623-9b23-893eb5699d64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d8d500d9-4925-4754-a0d4-c66ed6552b3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'qui']</value>
      <webElementGuid>5a592f15-3ee7-48c5-b8e4-29768b60b3af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
