<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Vai al risultato</name>
   <tag></tag>
   <elementGuidId>f5c181aa-00fa-4115-96b7-4a2cb70c8710</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.go</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='calcola()']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b836a521-7013-4696-aa3f-c483d3ea571c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>go</value>
      <webElementGuid>36013908-a5fe-4248-a2a8-f0dba90fb692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>calcola()</value>
      <webElementGuid>161c0836-ab33-401e-85d2-922048a004f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vai al risultato</value>
      <webElementGuid>1a9fa565-2857-4dd7-b559-eba9d16dd577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;km&quot;)/div[@class=&quot;big-box&quot;]/a[@class=&quot;go&quot;]</value>
      <webElementGuid>1846f907-3583-4b72-b7c4-39539682664b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='calcola()']</value>
      <webElementGuid>a0c5ce94-7696-424c-9fbc-5639b0e2b487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='km']/div/a</value>
      <webElementGuid>92a4a33c-c46b-48e3-96a5-8e0b81fcdd4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Vai al risultato')]</value>
      <webElementGuid>73637fa0-6fc7-4d77-a70d-9c3a51cfc8b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quanti km hai percorso?'])[1]/following::a[1]</value>
      <webElementGuid>bf2098f9-8ae2-4047-83b0-52483c615a71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hai già scoperto quanta CO2 hai causato?'])[1]/following::a[1]</value>
      <webElementGuid>8f6c7dca-0fd2-4a2e-afb0-eba7b2413b3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chi siamo?'])[1]/preceding::a[1]</value>
      <webElementGuid>7a94c78b-7640-4fce-8c8e-0a95f105f032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Info'])[1]/preceding::a[1]</value>
      <webElementGuid>8b50a3a0-cfcb-483f-812e-42b39163e3bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Vai al risultato']/parent::*</value>
      <webElementGuid>911cea7d-56e1-4f11-8899-ea5db0ad7c2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>cf5e52fb-72d9-4930-9270-36f70d218e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Vai al risultato' or . = 'Vai al risultato')]</value>
      <webElementGuid>68ab89f4-325e-4452-8c68-edbbb31b4b23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
