<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Mare_risorseimgship.png</name>
   <tag></tag>
   <elementGuidId>4ec5644e-4fbc-4d5b-bd28-b8ea7f8b5282</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='risorse\img\ship.png']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9121c031-bfaf-45c7-8a19-554c5015ea61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mezzo</value>
      <webElementGuid>51684315-5563-48c4-9b28-48070807149b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>risorse\img\ship.png</value>
      <webElementGuid>c1252a7d-bb7f-46f1-981c-08ec96c0f95a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>attiva(this)</value>
      <webElementGuid>9f82677f-6fa7-4a58-af5a-991864f3bb36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;risorse\img\ship.png&quot;)</value>
      <webElementGuid>c969d911-39ad-466d-85a5-73d2154384d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='risorse\img\ship.png']</value>
      <webElementGuid>b733a71b-78bf-42f8-b09b-bc2b871f9a70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='all-page']/div/div/div[2]/div[5]</value>
      <webElementGuid>f7876948-05cd-46fe-a1a7-c38db7802cca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mare'])[1]/following::div[6]</value>
      <webElementGuid>8b2185d7-0f6b-4958-b269-88be6071d6b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aria'])[1]/following::div[6]</value>
      <webElementGuid>f7c4b4e0-225b-436f-9015-440c1a5e32a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hai già scoperto quanta CO2 hai causato?'])[1]/preceding::div[6]</value>
      <webElementGuid>70aa6fa8-5da1-42e9-822a-b371a1ff0b31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quanti km hai percorso?'])[1]/preceding::div[10]</value>
      <webElementGuid>180ec1cd-28e5-40ce-862f-1afbf8cec5fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]</value>
      <webElementGuid>e059d4b7-f1f1-41ab-a3fc-f60208a959ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'risorse\img\ship.png']</value>
      <webElementGuid>2cfeae9c-dffd-425f-83be-eefb645e57aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
