<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Hai gi scoperto quanta CO2 hai causato_qui</name>
   <tag></tag>
   <elementGuidId>3966f2a1-7e15-438a-80e1-b40591146f78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#qui</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='qui']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>77c1d2fe-4856-4dc7-98d2-0aed4805932d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>274c3666-2a0d-421b-8293-d4e05596c2ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>qui</value>
      <webElementGuid>492f0135-216f-459b-97f2-9d92d212d37d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2e15ed84-e19a-46c6-a07f-fc88592c85af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qui&quot;)</value>
      <webElementGuid>259f6c41-9387-473b-80f7-dbc8737614c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='qui']</value>
      <webElementGuid>8af498b7-9855-4d42-b2c7-dbffc54e3ab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='all-page']/div[3]/div/div/input</value>
      <webElementGuid>f26dcc60-2845-4275-8ba6-c1d33df4f299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>95a6048c-32e1-4f15-b123-e868ebc162ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'qui']</value>
      <webElementGuid>4d42daab-7ab0-425f-9f31-4dfc285cdfcc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
