<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Calcolo CO2_checkmark</name>
   <tag></tag>
   <elementGuidId>fa08691e-56bd-4ec9-9d13-693473fd8d02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Piemonte > div.reg-card > div.radio-group > label.radio > span.checkmark</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>334545d7-72a2-4fec-9584-074c06fc2371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkmark</value>
      <webElementGuid>a31515a8-17fb-4a01-8866-44ed37120bf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Piemonte&quot;)/div[@class=&quot;reg-card&quot;]/div[@class=&quot;radio-group&quot;]/label[@class=&quot;radio&quot;]/span[@class=&quot;checkmark&quot;]</value>
      <webElementGuid>cbf5e938-ec1f-4ce5-8bfc-f7d4a3163db4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Piemonte']/div/div/label/span</value>
      <webElementGuid>2c8b6bb7-f9f3-42ac-b29b-d6784c20144f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/label/span</value>
      <webElementGuid>abf831b3-d35f-4195-ac36-e12c116d1c98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
