<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Calcolo CO2_checkmark_1</name>
   <tag></tag>
   <elementGuidId>59efb8e3-b6ee-451f-878a-5581f06fa12e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Emilia Romagna']/div/div/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>be094b80-5a05-45d4-8d84-6223b38495e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkmark</value>
      <webElementGuid>ff3ae864-d0fa-41f5-af65-97be20933443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Emilia Romagna&quot;)/div[@class=&quot;reg-card&quot;]/div[@class=&quot;radio-group&quot;]/label[@class=&quot;radio&quot;]/span[@class=&quot;checkmark&quot;]</value>
      <webElementGuid>b2d1a963-f95a-45e2-b52a-b220530d9dab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Emilia Romagna']/div/div/label/span</value>
      <webElementGuid>68a79b3a-11f5-4c0d-8cc7-4e5d20d09a52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/label/span</value>
      <webElementGuid>295896f5-9806-4b8a-8a85-1ac48ba89444</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
