<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Cerca</name>
   <tag></tag>
   <elementGuidId>e8f94910-4ba9-4f3c-aaf0-bb1c07c9139d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.submit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@onclick='seleziona()']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>61fb5552-e3b1-4fd2-a5e7-7683e9892104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>5cf5f2e5-5661-47c5-9f7b-57c360f386f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>seleziona()</value>
      <webElementGuid>f473eb4e-60f4-4f1c-b539-707d7f5dee25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cerca</value>
      <webElementGuid>4ec0ad86-3b0a-4f88-8c67-5e3a73ddf621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;all-mon&quot;]/div[@class=&quot;border&quot;]/div[@class=&quot;all-filter&quot;]/div[@class=&quot;submit&quot;]</value>
      <webElementGuid>dec085a3-a483-4fd3-bb65-17624e020934</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@onclick='seleziona()']</value>
      <webElementGuid>736a94bf-d9fb-45f9-a759-e1c92ff1a081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nazionale'])[1]/following::div[1]</value>
      <webElementGuid>104d1cd5-2bef-4e71-a659-12acc4ac9011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Veneto'])[1]/following::div[2]</value>
      <webElementGuid>e55fed9e-6fdc-45d7-9073-e00b2126cb21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Per navigare, premi i tasti freccia.'])[1]/preceding::div[95]</value>
      <webElementGuid>871cd93b-ae9a-4ba5-9e96-703631df5c0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='←'])[1]/preceding::div[100]</value>
      <webElementGuid>e2dbe531-b7c4-4a53-82a1-4028ed02b939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cerca']/parent::*</value>
      <webElementGuid>2d3250b6-dfca-441f-85b3-dd04f8a71ff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]</value>
      <webElementGuid>67054793-1562-4051-8735-f9d017809172</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Cerca' or . = 'Cerca')]</value>
      <webElementGuid>9a4b20e9-30bc-459a-96db-ccc3540b42cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
