<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Calcolo CO2_anno</name>
   <tag></tag>
   <elementGuidId>5ea89df3-4ede-4d60-aaaf-1dfa015209f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#anno</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='anno']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b1d050fa-d38c-49cf-9975-417ceb735391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7e5a2d7e-1af2-48fc-9010-a5106d92314d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filterBox</value>
      <webElementGuid>279d6467-95ad-4871-b8f3-64372e6066dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Anno</value>
      <webElementGuid>6f341ec4-244f-465b-a89e-34ffec29ee73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>anno</value>
      <webElementGuid>d06f42ce-b593-44d7-bd5b-ae97fa2c3735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;anno&quot;)</value>
      <webElementGuid>eedc7c2b-41eb-41d7-8a45-60325ccf1040</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='anno']</value>
      <webElementGuid>1c905653-5637-4004-ab0d-536869970a8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f6b28e91-a279-4535-b677-99787ec526ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'anno']</value>
      <webElementGuid>b41438c6-3bed-4e44-a959-b97c272381d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
