<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Calcolo CO2_fa-solid fa-cart-shopping</name>
   <tag></tag>
   <elementGuidId>d98998d5-5bab-40dd-a218-2b572ff6f796</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[2]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa-solid.fa-cart-shopping</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>4d1bba75-a502-4d17-828a-84e8f75263c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa-solid fa-cart-shopping</value>
      <webElementGuid>f6c41b35-e41b-4ff2-8e5f-d2554643c16e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/header[@class=&quot;all-headerbody&quot;]/div[@class=&quot;user&quot;]/a[2]/i[@class=&quot;fa-solid fa-cart-shopping&quot;]</value>
      <webElementGuid>8e52259b-ad0a-49b2-9480-ce0f3a2f50ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/i</value>
      <webElementGuid>bb26daf6-a19d-47ee-9562-7a7181381616</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
