<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Adotta un albero_1</name>
   <tag></tag>
   <elementGuidId>922b818c-adae-4daa-b72a-3177528177ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cat']/div/div[6]/div[2]/div[2]/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d9017f65-7409-4eaa-9d24-2e0bcb604ab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>regione.jsp?nome=mandarino</value>
      <webElementGuid>ef282aca-8b94-46d5-997d-eea1c0337c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn_secondary</value>
      <webElementGuid>44f84f2c-a3cb-47d8-b5f0-721a2406fe13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Adotta un albero</value>
      <webElementGuid>29dfb066-d1ae-492c-84ce-b14d141042ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cat&quot;)/div[@class=&quot;container-card&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;btn_area&quot;]/a[@class=&quot;btn_secondary&quot;]</value>
      <webElementGuid>be27e6f8-7d85-4fb4-981e-cc60e0aa2061</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cat']/div/div[6]/div[2]/div[2]/a[2]</value>
      <webElementGuid>18327c75-fddf-456e-9cdc-ac0977ada9d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Adotta un albero')])[6]</value>
      <webElementGuid>9922874c-7211-4f29-a6fb-7a852472f31a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mandarino'])[1]/following::a[2]</value>
      <webElementGuid>54698b31-86e4-4b55-a8a0-a5b9a2ccd61f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mandorlo'])[1]/preceding::a[1]</value>
      <webElementGuid>fe01b65a-e282-40ba-bb7c-a8ccd87be349</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'regione.jsp?nome=mandarino')]</value>
      <webElementGuid>db64a8a2-41e7-4506-8bf7-0b5a8d7de962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div[2]/a[2]</value>
      <webElementGuid>84114b3b-fcb6-414f-a9e3-c204ffde2cc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'regione.jsp?nome=mandarino' and (text() = 'Adotta un albero' or . = 'Adotta un albero')]</value>
      <webElementGuid>8e7fd64e-f322-4976-bb19-cf56b3a68e55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
