<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Calcolo CO2_checkmark</name>
   <tag></tag>
   <elementGuidId>b49ce002-0feb-4dac-9574-498e2996631a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Piemonte > div.reg-card > div.radio-group > label.radio > span.checkmark</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Piemonte']/div/div/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>785023d0-201e-415e-967a-244b2e39d6bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkmark</value>
      <webElementGuid>edd96891-4f0d-4721-a5ff-4cde802a87f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Piemonte&quot;)/div[@class=&quot;reg-card&quot;]/div[@class=&quot;radio-group&quot;]/label[@class=&quot;radio&quot;]/span[@class=&quot;checkmark&quot;]</value>
      <webElementGuid>574df5ab-768a-4f6e-b295-3880adf7a5e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Piemonte']/div/div/label/span</value>
      <webElementGuid>1a6492e4-3a4c-4b9a-9dea-6ac5dba7870f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/label/span</value>
      <webElementGuid>cba236a3-37fc-44b7-bc8a-f79c406a63dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
