<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Calcolo CO2_fa-solid fa-cart-shopping</name>
   <tag></tag>
   <elementGuidId>c3d87b38-f927-491b-921e-e4ffe9f7403a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[2]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa-solid.fa-cart-shopping</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>18800a63-c612-47af-bac8-9c3ee063e0ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa-solid fa-cart-shopping</value>
      <webElementGuid>fb857966-2dc3-4a5d-b9cf-f32f63ce5ea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/header[@class=&quot;all-headerbody&quot;]/div[@class=&quot;user&quot;]/a[2]/i[@class=&quot;fa-solid fa-cart-shopping&quot;]</value>
      <webElementGuid>ad8f418e-bdb7-498e-90a3-e0ad14f6dc09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/i</value>
      <webElementGuid>b3170fbd-efa6-47d1-82c7-afc983e7fdcc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
