<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Adotta</name>
   <tag></tag>
   <elementGuidId>312c4637-460a-4422-b14d-9008307a4d28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Adotta')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.list.active > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>172a748c-3a0a-4e6d-93c4-d3665959f302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>catalogo.jsp</value>
      <webElementGuid>6c958133-f4a1-4ddb-b837-d64465404bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Adotta</value>
      <webElementGuid>ace1b9cd-88ec-41ad-bf92-e0c9e7762bd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/header[@class=&quot;all-headerbody&quot;]/ul[@class=&quot;nav-menu&quot;]/li[@class=&quot;list active&quot;]/a[1]</value>
      <webElementGuid>94da0e11-1da3-493f-a17e-a2e155cf6e09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Adotta')]</value>
      <webElementGuid>213b5f3f-aa60-40ce-8c04-fb588fb5732f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[1]</value>
      <webElementGuid>a54d9a43-b618-4947-a4a2-a40a8ad0b90a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monitoraggio'])[1]/preceding::a[1]</value>
      <webElementGuid>b97a5050-01dd-4e2a-9f49-dcabbadc3067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calcolo CO2'])[1]/preceding::a[2]</value>
      <webElementGuid>fce51b6d-d23c-4312-811a-7d8d3e57fa7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Adotta']/parent::*</value>
      <webElementGuid>4ad47693-3f1e-421f-bbb7-b44a76a9c6f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'catalogo.jsp')]</value>
      <webElementGuid>4cd34e68-0ca2-4fa5-97dd-939dce43b618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>3e2a7bb2-3607-4e1c-9dfb-d935fee2e032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'catalogo.jsp' and (text() = 'Adotta' or . = 'Adotta')]</value>
      <webElementGuid>3f1477e6-d710-427b-90b3-6fc4e9b8ecd5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
