<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Campania</name>
   <tag></tag>
   <elementGuidId>9cc636b6-bc2d-44f0-9e74-6d1159d6d06f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@onclick=&quot;showReg('Campania')&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>eb5eebed-f7ba-4781-9832-31e100a38440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>showReg('Campania')</value>
      <webElementGuid>c380bc20-7aed-4b4a-aa12-53bbeb367d14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Campania</value>
      <webElementGuid>80d45d92-04f2-4a10-a69f-eac7bf38ffdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;all-mon&quot;]/div[@class=&quot;border&quot;]/div[@class=&quot;all-filter&quot;]/div[@class=&quot;dropdown-reg active&quot;]/div[@class=&quot;option&quot;]/div[4]</value>
      <webElementGuid>0d326b15-9174-4d4f-aa33-85c35e289a84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@onclick=&quot;showReg('Campania')&quot;]</value>
      <webElementGuid>781b4c4a-a0f9-4c21-8b89-4465f7d22967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calabria'])[1]/following::div[1]</value>
      <webElementGuid>52725734-6627-41fa-8815-7688f009aa0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Basilicata'])[1]/following::div[2]</value>
      <webElementGuid>9b6aad43-69e9-4853-999e-27b628483381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Emilia Romagna'])[1]/preceding::div[1]</value>
      <webElementGuid>8bca0693-7172-46fc-b8b4-f9024b0f843b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Friuli Venezia Giulia'])[1]/preceding::div[2]</value>
      <webElementGuid>80008a4f-b3f4-4696-90ee-c680a3a30430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Campania']/parent::*</value>
      <webElementGuid>760e94d0-3981-49a1-ba3d-f0c1d92aeadb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]</value>
      <webElementGuid>0a758dab-b832-4375-8cf4-2385ff58c6b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Campania' or . = 'Campania')]</value>
      <webElementGuid>41eab23f-fe08-4278-aa69-e5b70a19fa25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
