<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Calcolo CO2_regione</name>
   <tag></tag>
   <elementGuidId>778de607-6a11-48ae-ae54-24223e3b7733</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#regione</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='regione']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3a573803-ceb5-4fcb-a5bd-a27b786d0d25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>766a67ef-e600-4146-8784-0a6a481ccfce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filterBox-reg</value>
      <webElementGuid>633081e4-e50c-4f54-893f-dee211500a03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Regioni</value>
      <webElementGuid>7ebba5eb-f086-4041-9e74-04f763a40318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>regione</value>
      <webElementGuid>2d5877c0-3d20-4ac3-ab42-6d510ad890aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;regione&quot;)</value>
      <webElementGuid>83b3c01a-c575-4520-8c2e-1009262a242c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='regione']</value>
      <webElementGuid>de9b8e95-b37f-4433-b4af-c4e05fdff269</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>276c8173-b4aa-4367-aaa8-2a8ccf062cd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'regione']</value>
      <webElementGuid>91240a54-fda1-45d4-926a-72390460d481</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
