<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Calcolo CO2_anno</name>
   <tag></tag>
   <elementGuidId>5a9a6e17-b081-44c0-b1b5-6bce1f4d1625</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#anno</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='anno']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>267653a7-c4bd-47d6-9a91-fbb2be408a67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9e2f8288-13cd-4b64-bfe6-88d2e5c876d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filterBox</value>
      <webElementGuid>6d5152c3-4735-40c3-a314-854dc19a1a78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Anno</value>
      <webElementGuid>f85a789d-2470-45eb-9fae-86aefbe0f239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>anno</value>
      <webElementGuid>7e050af5-08a9-483f-b302-1f4821886d2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;anno&quot;)</value>
      <webElementGuid>c3cc1676-9278-4b99-99d0-0a93568c93d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='anno']</value>
      <webElementGuid>f454735b-a86a-465b-8de9-6ce7de3cd367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>9cfc8c69-e90c-4822-8547-a43296329619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'anno']</value>
      <webElementGuid>4f7d6f82-76d1-4b0c-b597-0b73bdebbca5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
