<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Completa lacquisto</name>
   <tag></tag>
   <elementGuidId>468883bd-2573-48bf-abcb-95a2e45bfc17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='payment-submit-btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#payment-submit-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c54b919c-bf68-4645-bd83-86ea4d4faa73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ppvx_btn___5-11-4 CheckoutButton_noMargin_mv-3h</value>
      <webElementGuid>d202f33e-facf-4c71-b319-6095690492ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payment-submit-btn</value>
      <webElementGuid>ed43bfb6-4745-41aa-bf89-fca2b4016791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>submit-button-initial</value>
      <webElementGuid>13887475-5dd4-4c15-9351-ad52e1548372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3bbf0f46-c5be-4bc8-bf0d-4356fb35f784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Completa l'acquisto</value>
      <webElementGuid>d6c5ae33-8e52-4f07-9f6d-0084ed66fe62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-submit-btn&quot;)</value>
      <webElementGuid>b8df6808-1232-4c6f-8862-349c1c97fef4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='payment-submit-btn']</value>
      <webElementGuid>c78bae7f-fe9e-4cae-bfaa-4aa9c214cd3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hermione-container']/div/main/div[4]/div[2]/button</value>
      <webElementGuid>87580242-b4ee-4318-9d29-bf8148d7c367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='O Paga in 3 rate'])[1]/following::button[1]</value>
      <webElementGuid>c31aaf23-0d4f-4936-8d28-9280fdd6e185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aggiungi carta'])[1]/following::button[1]</value>
      <webElementGuid>c4dfd017-1f90-4004-81e3-75bda4627f86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'payment-submit-btn', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>4fd0695b-7871-4c8d-a344-73f1773d4501</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>41019047-efb1-416d-ad21-98ec92f32ef2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'payment-submit-btn' and (text() = concat(&quot;Completa l&quot; , &quot;'&quot; , &quot;acquisto&quot;) or . = concat(&quot;Completa l&quot; , &quot;'&quot; , &quot;acquisto&quot;))]</value>
      <webElementGuid>564c7417-8608-4619-8667-ac0dd63ae8d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
