<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Completa lacquisto</name>
   <tag></tag>
   <elementGuidId>468883bd-2573-48bf-abcb-95a2e45bfc17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#payment-submit-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='payment-submit-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2d2b31ff-1c2f-4aa0-889c-e63b15459650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ppvx_btn___5-11-4 CheckoutButton_noMargin_mv-3h</value>
      <webElementGuid>bcff9398-7783-4a21-8bf0-766d58391df2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payment-submit-btn</value>
      <webElementGuid>ce6df48f-6d0f-4bb7-9be2-f05775660638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>submit-button-initial</value>
      <webElementGuid>80fbc1b5-8a12-4d6e-b9bc-2269f5a41a38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1a8a839c-d47f-4f8b-8250-bea6acf20dd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Completa l'acquisto</value>
      <webElementGuid>f48d1428-7290-47b6-9823-7b2c9fb239fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-submit-btn&quot;)</value>
      <webElementGuid>a25394f1-23aa-4992-9f50-22e98f3f2ad8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='payment-submit-btn']</value>
      <webElementGuid>006199f2-d15c-4633-895c-908bddcc6ed7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hermione-container']/div/main/div[4]/div[2]/button</value>
      <webElementGuid>76582322-3418-49d8-9bbe-67a9f5254a34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='O Paga in 3 rate'])[1]/following::button[1]</value>
      <webElementGuid>5964ba98-8f15-482f-acaa-7f3596ef62e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aggiungi carta'])[1]/following::button[1]</value>
      <webElementGuid>d4d2c606-af77-41f5-9163-85f6dc405fb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'payment-submit-btn', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>269ab350-f339-4b92-b670-60ffc4af3ab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>88b7b66c-c91b-42b1-84a7-e089ef457591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'payment-submit-btn' and (text() = concat(&quot;Completa l&quot; , &quot;'&quot; , &quot;acquisto&quot;) or . = concat(&quot;Completa l&quot; , &quot;'&quot; , &quot;acquisto&quot;))]</value>
      <webElementGuid>a9121565-79a3-4339-814c-6feafdd48437</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
