<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Adotta</name>
   <tag></tag>
   <elementGuidId>a9ad51b2-74ef-4882-b286-49270f540268</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.list.active > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Adotta')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6fb32b52-40a5-4f24-bbee-e1ca7c87828c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>catalogo.jsp</value>
      <webElementGuid>dfef8fac-5bd3-474c-b580-13aa0121bd54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Adotta</value>
      <webElementGuid>054a5f6d-daa9-4908-9f9e-9cfaf2c9b26a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/header[@class=&quot;all-headerbody&quot;]/ul[@class=&quot;nav-menu&quot;]/li[@class=&quot;list active&quot;]/a[1]</value>
      <webElementGuid>8a3989d7-c367-4f18-87a4-eae846592f5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Adotta')]</value>
      <webElementGuid>dc5e9d7f-6b56-47d6-bda3-1b6f4aa3965d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[1]</value>
      <webElementGuid>290b1253-76ba-4e5e-9186-dd9f12df00a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monitoraggio'])[1]/preceding::a[1]</value>
      <webElementGuid>7153d997-f69f-4fec-9b69-438931257239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calcolo CO2'])[1]/preceding::a[2]</value>
      <webElementGuid>2eb58b37-6740-4dae-86d3-fcbfdfcd8d99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Adotta']/parent::*</value>
      <webElementGuid>05e0190b-f78f-447a-baf3-2a3dd6712084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'catalogo.jsp')]</value>
      <webElementGuid>5011d9a4-cd28-473e-b10f-d9a8a37983d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>46b965de-c5f4-49eb-8024-29539e1a2cf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'catalogo.jsp' and (text() = 'Adotta' or . = 'Adotta')]</value>
      <webElementGuid>9b769b59-cab4-4fe8-b996-512d863e4460</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
