<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Piemonte_fa fa-trash</name>
   <tag></tag>
   <elementGuidId>24ac7668-97e1-4dac-8d8f-02ee61eebd73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-trash</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[3]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>9733c1e5-6e73-4f78-bc8e-4df9be025ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-trash</value>
      <webElementGuid>4514554a-241d-4b5d-b902-b483a37443c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;all-cart&quot;]/div[@class=&quot;px-4 px-lg-0&quot;]/div[@class=&quot;pb-5&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 p-5 bg-white rounded shadow-sm mb-5&quot;]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;table&quot;]/tbody[1]/tr[1]/td[@class=&quot;border-0 align-middle&quot;]/a[@class=&quot;text-dark&quot;]/i[@class=&quot;fa fa-trash&quot;]</value>
      <webElementGuid>f91c85fe-826b-4f33-91c3-a392d6762ff8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a/i</value>
      <webElementGuid>20beb30d-b084-4771-9b37-753f8a7496c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
